---
version: "2"
run:
  go: "1.24"
linters:
  default: all
  disable:
    - containedctx
    - contextcheck # probably should not ignore but... old cruft and its working fine :)
    - cyclop # already using gocyclo, and its good enough!
    - depguard
    - exhaustruct
    - ireturn
    - musttag # also probably should remove but... for now
    - nonamedreturns
    - paralleltest
    - protogetter
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl # deprecated, wsl_v5 included in all ofc
  settings:
    funlen:
      lines: 150
      statements: 50
    gocritic:
      disabled-checks:
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    importas:
      alias:
        - pkg: k8s.io/client-go/dynamic/(\w+)
          alias: clientgo$1
        - pkg: sigs.k8s.io/controller-runtime
          alias: ctrlruntime
        - pkg: sigs.k8s.io/controller-runtime/pkg/(\w+)
          alias: ctrlruntime$1
        - pkg: sigs.k8s.io/controller-runtime/pkg/controller/controllerutil
          alias: ctrlruntimeutil
        - pkg: k8s.io/api/(\w+)/(\w+)
          alias: k8s$1$2
        - pkg: k8s.io/apimachinery/pkg/types
          alias: apimachinerytypes
        - pkg: k8s.io/apimachinery/pkg/apis/(\w+)/(\w+)
          alias: $1$2
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apimachineryerrors
        - pkg: k8s.io/apimachinery/pkg/runtime
          alias: apimachineryruntime
        - pkg: k8s.io/apimachinery/pkg/runtime/scheme
          alias: apimachineryruntimescheme
        - pkg: github.com/srl-labs/clabernetes/(\w+)
          alias: clabernetes$1
        - pkg: github.com/srl-labs/clabernetes/(\w+)/(\w+)
          alias: clabernetes$1$2
        - pkg: github.com/srl-labs/clabernetes/(\w+)/(\w+)/(\w+)
          alias: clabernetes$1$2$3
      no-unaliased: true
    lll:
      line-length: 100
      tab-width: 4
    staticcheck:
      checks:
        - -ST1000
  exclusions:
    rules:
      - linters:
          - dupl
          - funlen
          - gochecknoglobals
          - lll
          - maintidx
          - mnd
          - structcheck
          - unparam
          - unused
        path: _test\.go
      - linters:
          - revive
        path: logging/fake.go
      - linters:
          - gochecknoglobals
        text: schemeBuilder is a global variable
      - linters:
          - gochecknoglobals
        text: localSchemeBuilder is a global variable
      - linters:
          - gochecknoglobals
        text: SchemeGroupVersion is a global variable
      - linters:
          - gochecknoglobals
        text: AddToScheme is a global variable
      - linters:
          - revive
        text: package-comments
      - linters:
          - lll
        source: kubebuilder
      - linters:
          - perfsprint
        text: can be replaced with string concatenation
      - linters:
          - revive
        path: util/
        text: meaningless package names
    paths:
      - .private
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
